{% set name = "addicty" %}
{% set version = "2023.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/addicty-{{ version }}.tar.gz
  sha256: dcd4f39c9127c9ca0489d752367aa87f961d22581ab4252b1c3fa111ca2edf8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - python >=3.7
    - pyyaml
    - yamllint

test:
  imports:
    - addicty
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jpn--/addicty
  summary: Addicty is a dictionary whose items can be set using both attribute and item syntax.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jpn--
